sonar.projectKey=sant124_app-gingo
sonar.organization=sant124
sonar.projectName=app-gingo
sonar.sources=.
sonar.exclusions=**/vendor/**,**/docs/**,**/*_test.go
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
sonar.sourceEncoding=UTF-8
