sonar.projectKey=sant125_app-gingo
sonar.organization=sant125
sonar.projectName=app-gingo
sonar.sources=.
sonar.exclusions=**/vendor/**,**/docs/**,**/*_test.go,**/coverage.html
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
sonar.sourceEncoding=UTF-8
